/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.view;

import br.com.senac.bean.Server;
import java.io.IOException;

/**
 *
 * @author thiag
 */
public class SrvView extends javax.swing.JFrame {

    /**
     * Creates new form SrvView
     */
    public SrvView() {
        initComponents();
    }

    private Server srv;
    private Thread threadTest;
    private String textTela = "";

    public void showText(String text) {
        this.cxText.setText(text);
        this.cxText.setVisible(true);
    }

    public void setText(String text) {
        this.textTela += "\n" + text;
        this.cxText.setText(this.textTela);
        this.cxText.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geralPainel = new javax.swing.JPanel();
        txPainel = new javax.swing.JLabel();
        btStart = new javax.swing.JButton();
        btStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxText = new javax.swing.JTextArea();
        cxPort = new javax.swing.JTextField();
        txPorta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Server");

        geralPainel.setBackground(new java.awt.Color(0, 102, 51));

        txPainel.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        txPainel.setForeground(new java.awt.Color(255, 255, 0));
        txPainel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txPainel.setText("Chat Server");

        btStart.setText("Start");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        btStop.setText("Stop");
        btStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStopActionPerformed(evt);
            }
        });

        cxText.setColumns(20);
        cxText.setRows(5);
        jScrollPane1.setViewportView(cxText);

        cxPort.setText("5000");

        txPorta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txPorta.setForeground(new java.awt.Color(255, 255, 0));
        txPorta.setText("Porta:");

        javax.swing.GroupLayout geralPainelLayout = new javax.swing.GroupLayout(geralPainel);
        geralPainel.setLayout(geralPainelLayout);
        geralPainelLayout.setHorizontalGroup(
            geralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralPainelLayout.createSequentialGroup()
                .addGroup(geralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(geralPainelLayout.createSequentialGroup()
                        .addComponent(txPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(geralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(geralPainelLayout.createSequentialGroup()
                                .addComponent(btStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btStop, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(geralPainelLayout.createSequentialGroup()
                                .addComponent(txPorta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxPort, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(geralPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        geralPainelLayout.setVerticalGroup(
            geralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralPainelLayout.createSequentialGroup()
                .addGroup(geralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, geralPainelLayout.createSequentialGroup()
                        .addGroup(geralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPorta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(geralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btStart)
                            .addComponent(btStop))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geralPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geralPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed

        this.srv = new Server(this);
        this.srv.setPort(Integer.parseInt(this.cxPort.getText()));
        this.threadTest = new Thread(this.srv);
        this.threadTest.start();
        showText(this.textTela);
    }//GEN-LAST:event_btStartActionPerformed

    private void btStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStopActionPerformed
        try {
            this.srv.shutdownServer();
            this.textTela += "\nEncerrando servidor";
            showText(this.textTela);
        } catch (IOException ex) {
            this.textTela += "\nErro ao encerrar servidor";
            showText(this.textTela);
        }
    }//GEN-LAST:event_btStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SrvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SrvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SrvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SrvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SrvView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStart;
    private javax.swing.JButton btStop;
    private javax.swing.JTextField cxPort;
    private javax.swing.JTextArea cxText;
    private javax.swing.JPanel geralPainel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txPainel;
    private javax.swing.JLabel txPorta;
    // End of variables declaration//GEN-END:variables
}
